[build]
  command = "cd trysnowball-frontend && npm run build"
  publish = "trysnowball-frontend/build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "https://trysnowball.co.uk/*"
  to = "https://trysnowball.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.trysnowball.co.uk/*"
  to = "https://trysnowball.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true