#!/bin/bash

echo "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Testing Clean UK Debt API Format"
echo "========================================="
echo ""
echo "To test the live API, you'll need a valid JWT token."
echo "You can get one by:"
echo "1. Opening the app in your browser"
echo "2. Logging in"
echo "3. Opening DevTools Console"
echo "4. Running: localStorage.getItem('trysnowball-jwt')"
echo ""
echo "Then run this command with your token:"
echo ""
echo "curl https://app.trysnowball.co.uk/api/debts \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  | jq '.'"
echo ""
echo "Expected format (clean UK):"
echo "["
echo "  {"
echo "    \"id\": \"debt-123\","
echo "    \"name\": \"Barclaycard\","
echo "    \"amount\": 1520.55,"
echo "    \"apr\": 24.9,"
echo "    \"min_payment\": 55,"
echo "    \"order_index\": 1,"
echo "    \"limit\": 2000"
echo "  }"
echo "]"
echo ""
echo "NOT the old format with amount_cents, apr_bps, min_payment_cents!"