name: dependabot-automerge
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Decide merge policy
        id: policy
        run: |
          # default: don't merge
          echo "merge=false" >> $GITHUB_OUTPUT
          # labels applied by CI will drive merge
      - name: Enable auto-merge when labeled
        if: contains(github.event.pull_request.labels.*.name, 'automerge-ok')
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash