name: Update Substack Articles

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths: 
      - 'update-articles.js'
      - '.github/workflows/update-articles.yml'

jobs:
  update-articles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install xml2js
    
    - name: Update articles from RSS
      run: |
        echo "Starting RSS update process..."
        node update-articles.js
        echo "RSS update completed"
    
    - name: Check if articles were updated
      id: check_changes
      run: |
        if git diff --quiet public/articles.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected in articles.json"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected in articles.json"
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/articles.json
        git commit -m "🤖 Update Substack articles - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: No changes notification
      if: steps.check_changes.outputs.changed == 'false'
      run: echo "✅ No new articles found - no update needed"