name = "trysnowball-settings-main"
main = "user-settings.js"
compatibility_date = "2024-11-20"
workers_dev = false

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "auth_db"
database_id = "c22c4bca-0e0c-44db-957f-5e087c660fb0"

# Environment variables (set via wrangler secret put)
# JWT_SECRET - Secret key for signing JWTs (use: wrangler secret put JWT_SECRET)

[env.production]
name = "trysnowball-settings-prod"
routes = [
  { pattern = "trysnowball.co.uk/api/user_settings", zone_name = "trysnowball.co.uk" },
  { pattern = "www.trysnowball.co.uk/api/user_settings", zone_name = "trysnowball.co.uk" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "auth_db"
database_id = "c22c4bca-0e0c-44db-957f-5e087c660fb0"

[env.staging]
name = "trysnowball-settings-staging"
route = "staging-trysnowball.pages.dev/api/user_settings"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "auth_db"
database_id = "c22c4bca-0e0c-44db-957f-5e087c660fb0"