name = "trysnowball-debts-api"
main = "debts-api.js"
compatibility_date = "2024-11-20"
workers_dev = false

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "auth_db"
database_id = "c22c4bca-0e0c-44db-957f-5e087c660fb0"

# Environment variables (set via wrangler secret put)
# JWT_SECRET - Secret key for JWT verification (same as auth worker)
# MASTER_KEY_V1 - Master encryption key for AES-256-GCM (32 random bytes, base64)
# METRICS_HMAC_KEY - HMAC key for analytics event signing

[env.production]
name = "trysnowball-debts-api-prod"
routes = [
  { pattern = "trysnowball.co.uk/api/*", zone_name = "trysnowball.co.uk" },
  { pattern = "www.trysnowball.co.uk/api/*", zone_name = "trysnowball.co.uk" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "auth_db"
database_id = "c22c4bca-0e0c-44db-957f-5e087c660fb0"

[env.staging]
name = "trysnowball-debts-api-staging"
routes = [
  "staging-trysnowball.pages.dev/api/debts*",
  "staging-trysnowball.pages.dev/api/crypto/*",
  "staging-trysnowball.pages.dev/api/user/*",
  { pattern = "staging.trysnowball.co.uk/api/debts*", zone_name = "trysnowball.co.uk" },
  { pattern = "staging.trysnowball.co.uk/api/crypto/*", zone_name = "trysnowball.co.uk" },
  { pattern = "staging.trysnowball.co.uk/api/user/*", zone_name = "trysnowball.co.uk" }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "auth_db"
database_id = "c22c4bca-0e0c-44db-957f-5e087c660fb0"